#!/bin/sh

result=result.html	#resultをresult.htmlとする

tmpfile1=/tmp/sample.$$1
tmpfile2=/tmp/sample.$$2

if [ $# -eq 0 ]; then
	echo "Usage: $0 file [files ...]"	#""内を出力
	exit 1	#1としてシェルを閉じる
fi

trap "rm -f ${tmpfile1} ${tmpfile2}" 0 1 2 13 15	#信号を受け取るとシェルを閉じる

rm -f ${tmpfile1}	#確認なしに消去
for i in $@; do
	if [ -f ${i} ]; then
		echo ${i} >> ${tmpfile1}	#追加で書き込み
	else
		echo "can't find ${i}"	#""内を出力
	fi
done
test -f ${tmpfile1} || exit 0	#状況を1か0で返す
files="`sort < ${tmpfile1}`"

cat - > ${tmpfile2} <<EOF	#ヒアドキュメント
<html>
<head>
<title>File Contents</title>
</head>
<body>
<h1>File Contents</h1>
EOF

c=1
for i in ${files}; do
	echo "<a href=\"#${i}\">${c} ${i}</a><br>" >> ${tmpfile2}	#追加書き込み
	c=`expr ${c} + 1`
done

c=1
for i in ${files}; do
	echo "<h2><a name=\"${i}\">${c} ${i}</a></h2>" >> ${tmpfile2}	#追加書き込み
	echo '<pre>' >> ${tmpfile2}	#追加書き込み
	cat ${i} >> ${tmpfile2}	#追加書き込み
	echo '</pre>' >> ${tmpfile2}	#追加書き込み
	c=`expr ${c} + 1`
done

cat - >> ${tmpfile2}<<EOF	#ヒアドキュメント
</body>
</html>
EOF

cp ${tmpfile2} ${result}	#コピー
rm -f ${tmpfile2}	#確認なしに消去

exit 0
